# Generated by Django 3.2.6 on 2021-09-02 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='votesSum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='votesSum',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='votes',
        ),
        migrations.AddField(
            model_name='comment',
            name='votes',
            field=models.ManyToManyField(related_name='comment_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.subreddit'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='votes',
        ),
        migrations.AddField(
            model_name='post',
            name='votes',
            field=models.ManyToManyField(related_name='post_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
