# Generated by Django 3.2.6 on 2021-09-02 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20210902_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='comment_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
