# Generated by Django 3.2.6 on 2021-09-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210903_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postsdownvotes',
            options={'verbose_name_plural': 'Post Downvotes'},
        ),
        migrations.AlterModelOptions(
            name='postsupvotes',
            options={'verbose_name_plural': 'Post Upvotes'},
        ),
        migrations.AddConstraint(
            model_name='postsdownvotes',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_post_downvote'),
        ),
        migrations.AddConstraint(
            model_name='postsupvotes',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_post_upvote'),
        ),
    ]
