# Generated by Django 3.2.6 on 2021-09-07 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_auto_20210903_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='CommentUpVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_upvote', to='main.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvote_user_comment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comment Upvotes',
            },
        ),
        migrations.CreateModel(
            name='CommentDownVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_downvote', to='main.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downvote_user_comment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comment Downvotes',
            },
        ),
        migrations.AddConstraint(
            model_name='commentupvote',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='unique_comment_upvote'),
        ),
        migrations.AddConstraint(
            model_name='commentdownvote',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='unique_comment_downvote'),
        ),
    ]
