# Generated by Django 3.2.6 on 2021-09-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210907_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='votesSum',
        ),
    ]
