# Generated by Django 3.2.6 on 2021-09-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_comment_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/subreddit/'),
        ),
    ]
