# Generated by Django 3.2.6 on 2021-09-09 19:30

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_subreddit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/post/'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('TP', 'Text'), ('IP', 'Image')], default='TP', max_length=2),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.upload_image_rename),
        ),
    ]
