# Generated by Django 3.2.6 on 2021-09-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/subreddit/'),
        ),
    ]
