# Generated by Django 3.2.6 on 2021-09-09 20:33

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_subreddit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='image',
            field=models.ImageField(blank=True, default='images/subreddit/default.png', null=True, upload_to=main.models.upload_image_rename),
        ),
    ]
