# Generated by Django 3.2.6 on 2021-09-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_alter_post_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="commented_at", new_name="created_at"
        )
    ]
