# Generated by Django 3.2.6 on 2021-10-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rename_date_notifications_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='image',
            field=models.ImageField(blank=True, default='images/subreddit/default.png', null=True, upload_to='images/subreddit/'),
        ),
    ]
