# Generated by Django 3.2.6 on 2021-10-13 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0027_post_saved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='saved_by',
            field=models.ManyToManyField(related_name='saved_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='saved_by',
            field=models.ManyToManyField(related_name='saved_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
